In [77]:
import pandas as pd
import requests as req
from bs4 import BeautifulSoup as BS

In [78]:
## Create the container of all Products
products_container = []
## create Script for get data from the link
def main(link): 
    page = req.get(link)
    soup = BS(page.text, 'html.parser')
    products = soup.select('.c-prd')
    for prd in products:
        ## get some data from atrribute of the element a with class core
        data_fm_a = prd.select_one('a.core')
        category = data_fm_a.get('data-ga4-item_category2')
        brand = data_fm_a.get('data-gtm-brand')
        prd_name = data_fm_a.get('data-gtm-name')
        ## get data from info div
        info_data = prd.select_one('div.info')
        desc = info_data.select_one('h3.name').text.strip()
        new_price =info_data.select_one('div.prc').text.strip()
        old_data =info_data.select_one('div.s-prc-w')
        if old_data :        
            old_price = old_data.select_one('div.old').text.strip() 
            discount = old_data.select_one('div._dsct' ).text.strip() 
        else: 
            old_price = None
            discount = None

        ### put all data in list of dictionary to use at printing
        products_container.append({
            'Category': category,
            'Brand': brand,
            'Name': prd_name,
            'New_Price': new_price,
            'Discount': discount,
            'Old_Price': old_price,
            
        })

In [ ]:
### printin data in file 
def printing():
    for i in range(1,20):
        print(i)
        link = f'https://www.jumia.com.eg/catalog/?q=mobile+phone&page={i}'
        main(link)
printing()
df = pd.DataFrame(products_container)
df.isnull().sum()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [75]:
df[df['Discount'].notna()]

,Category,Brand,Name,New_Price,Discount,Old_Price
0,Mobile Phones,Honor,"X6c Dual SIM 4G Smartphone – 256GB Storage, 6G...","EGP 7,099.00",9%,"EGP 7,810.00"
1,Mobile Phones,Infinix,HOT 60 Pro 256/ 8+8GB Mobile Phone Titanium Si...,"EGP 9,399.00",9%,"EGP 10,340.00"
2,Mobile Phones,XIAOMI,Redmi Note 15- 4G -Dual SIM-8 GB 256 GB- Black,"EGP 11,299.00",10%,"EGP 12,540.00"
3,Mobile Phones,XIAOMI,POCO C85 Dual SIM 256/8 Mobile phone - Black ...,"EGP 6,999.00",9%,"EGP 7,700.00"
4,Mobile Phones,Honor,"X6c Dual SIM 4G Smartphone – 128GB Storage, 6G...","EGP 6,499.00",9%,"EGP 7,150.00"
5,Mobile Phones,Samsung,"Galaxy A17 - 6.7"" 128GB/6GB Dual SIM 4G Mobile...","EGP 8,799.00",9%,"EGP 9,680.00"
6,Mobile Phones,Honor,"X6c Dual SIM 4G Smartphone – 256GB Storage, 6G...","EGP 7,099.00",9%,"EGP 7,810.00"
7,Mobile Phones,Samsung,"Galaxy A07 - 6.7"" inch 256GB/8GB Dual SIM 4G M...","EGP 7,999.00",11%,"EGP 9,020.00"
8,Mobile Phones,Honor,"X6c Dual SIM 4G Smartphone – 256GB Storage, 6G...","EGP 7,099.00",9%,"EGP 7,810.00"
9,Mobile Phones,XIAOMI,"Redmi Note 15 ,5G ,Dual SIM,8 GB 256 GB, black","EGP 13,999.00",9%,"EGP 15,400.00"
10,Mobile Phones,Samsung,Galaxy A36 Dual SIM 5G 256GB/8GB Mobile Phone ...,"EGP 17,499.00",9%,"EGP 19,250.00"
11,Mobile Phones,Infinix,GT 30 Pro 512/ 12GB Mobile Phone Dark Flare,"EGP 18,799.00",9%,"EGP 20,680.00"
12,Mobile Phones,Samsung,Galaxy A26 Dual SIM 5G 256GB/8GB Mobile Phone-...,"EGP 15,596.00",9%,"EGP 17,160.00"
13,Mobile Phones,Samsung,Galaxy A36 Dual SIM 5G 128GB/8GB Mobile Phone ...,"EGP 15,899.00",9%,"EGP 17,490.00"
14,Mobile Phones,XIAOMI,REDMI Note 15 4G (8+256G) – GLACIER Blue,"EGP 11,399.00",9%,"EGP 12,540.00"
15,Mobile Phones,Honor,"X6c Dual SIM, 128GB, 6GB RAM, 4G LTE - Moonlig...","EGP 6,759.00",13%,"EGP 7,770.00"
16,Mobile Phones,Honor,X7d Dual SIM 4G 256GB/8GB - Velvet Black,"EGP 9,650.00",9%,"EGP 10,620.00"
17,Mobile Phones,Samsung,Galaxy A26 Dual SIM 5G 128GB/6GB Mobile Phone ...,"EGP 12,199.00",9%,"EGP 13,420.00"
18,Mobile Phones,Samsung,Galaxy A26 Dual SIM 5G 128GB/6GB 6.7 inches Mo...,"EGP 13,362.00",9%,"EGP 14,700.00"
19,Mobile Phones,OPPO,"Reno14 F Dual SIM, 256GB, 8GB RAM, 5G - Lumino...","EGP 19,049.00",13%,"EGP 21,910.00"
20,Mobile Phones,Samsung,Galaxy A36 Dual SIM 5G 128GB/8GB Mobile Phone ...,"EGP 17,410.00",9%,"EGP 19,150.00"
21,Mobile Phones,XIAOMI,Redmi A5 4G Dual SIM Midnight Black 4GB RAM 64...,"EGP 5,451.00",22%,"EGP 6,999.00"
22,Mobile Phones,XIAOMI,"Redmi Note 15 Pro 5G ,Dual SIM,12 GB 256 GB, b...","EGP 18,399.00",9%,"EGP 20,240.00"
24,Mobile Phones,XIAOMI,REDMI Note 15 4G(8+256G) – forest green,"EGP 11,399.00",9%,"EGP 12,540.00"
25,Mobile Phones,Honor,X9d Dual SIM 5G 256GB/12GB - Reddish Brown,"EGP 19,699.00",5%,"EGP 20,684.00"
26,Mobile Phones,Samsung,Galaxy A26 Dual SIM 5G 256GB/8GB Mobile Phone-...,"EGP 15,596.00",9%,"EGP 17,160.00"
27,Mobile Phones,Samsung,"Galaxy S25 Plus ,5G ,12GB ,256GB,Dual SIM , MINT","EGP 46,999.00",9%,"EGP 51,700.00"
28,Mobile Phones,Honor,"X6c Dual SIM, 128GB, 6GB RAM, 4G LTE - Midnigh...","EGP 6,759.00",13%,"EGP 7,770.00"
30,Mobile Phones,XIAOMI,Redmi 15 4G Dual SIM 128GB/6GB Mobile phone - ...,"EGP 7,777.00",9%,"EGP 8,550.00"
31,Mobile Phones,Samsung,Galaxy A26 Dual SIM 5G 256GB/8GB Mobile Phone-...,"EGP 14,199.00",9%,"EGP 15,620.00"
32,Mobile Phones,Samsung,Galaxy A56 Dual SIM 5G 256GB/8GB 6.7 inches Mo...,"EGP 24,133.00",9%,"EGP 26,550.00"
33,Mobile Phones,XIAOMI,"Redmi Note 15 ,Dual SIM 5G ,8 GB 256 GB, Mist ...","EGP 13,999.00",9%,"EGP 15,400.00"
34,Mobile Phones,Honor,"X6c Dual SIM, 128GB, 6GB RAM, 4G LTE - Ocean Cyan","EGP 6,759.00",13%,"EGP 7,770.00"
35,Mobile Phones,Nokia,Noki a 106 Dual Sim 4G-Black,EGP 549.00,45%,EGP 999.00
36,Mobile Phones,Honor,"X6c Dual SIM, 256GB, 6GB RAM, 4G LTE - Moonlig...","EGP 7,289.00",13%,"EGP 8,380.00"
37,Mobile Phones,XIAOMI,"Redmi 15C Dual SIM, 256GB, 8GB RAM, 4G LTE - M...","EGP 7,929.00",13%,"EGP 9,120.00"
38,Mobile Phones,Honor,"X6c Dual SIM, 256GB, 6GB RAM, 4G LTE - Ocean Cyan","EGP 7,289.00",13%,"EGP 8,380.00"
39,Mobile Phones,realme,"C71 Dual SIM, 128GB, 6GB RAM, 4G LTE - Forest Owl","EGP 7,939.00",13%,"EGP 9,130.00"

In [ ]:
df[df['Discount'].isna()]

,Category,Brand,Name,New_Price,Discount,Old_Price
23,Mobile Phones,Infinix,"Smart 10 Dual Sim – 64GB, 3GB Ram,4G- Twilight...","EGP 24,320.00",None,None
29,Mobile Phones,Infinix,"SMART 10 64GB, 4GB RAM, Dual SIM 4G LTE-Sleek ...","EGP 15,800.00",None,None